### ISSUE TITLE
Embed Web Interface

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/core#38]
We're getting closer to the point where `core` and `web` work independently. It's time to bring them together. The web interface should be embedded into the binary so the only thing the user has to do is run the binary. Some things to figure out.

1. How to embed the compiled files from web into the binary? (`rust-embed` and `include_bytes!` are some ideas)

2. How to include / fetch the web interface? (git submodules maybe)

3. I don't want to wait for a > 1m recompile of the web interface when working on core. Please put building and embedding the web interface behind a flag.

## TODO:
* [x] #37 
* [x] https://github.com/forte-music/web/issues/57
* [x] Need a way for core to easily get a built web interface.
* [ ] Implement actual embedding.

**Comment by Mcat12** [comment]
Current plan is to use an S3 bucket for storing web builds, then core pulls one down during build and embeds it. Then the core build will contain the binary as an artifact.

**Comment by Mcat12** [comment]
Embedding will use [`rust-embed`](https://crates.io/crates/rust-embed).

**Comment by 0xcaff** [comment]
Um closed by #67
