### ISSUE TITLE
Implement Transcoding

### ISSUE THREAD

**Issue by 0xcaff** [forte-music/core#9]
## Overview

There needs to be something which takes a file on the disk and makes transcoded versions available at certain URLs. There should be transcoded versions with a few formats (AAC, MP3) and a few constant bitrates (320, 190).

## Resources
* https://github.com/meh/rust-ffmpeg/blob/master/examples/transcode-audio.rs
* https://github.com/rust-av/rust-av
* https://github.com/phanan/koel/blob/7d80f1d1439c210144da2ee3fde2439b600782ef/app/Services/Streamers/TranscodingStreamer.php#L33-L57
* https://github.com/captbaritone/transcode-to-mp3-stream/blob/master/src/Captbaritone/TranscodeToMp3Stream/Streamer.php
* https://github.com/khenriks/mp3fs/blob/ca59d124c7a9cf3540df8f8afc78646ac9f822dc/src/transcode.cc#L141-L195
* https://github.com/leandromoreira/ffmpeg-libav-tutorial/issues/24
* https://www.codeproject.com/Tips/489450/Creating-Custom-FFmpeg-IO-Context
* https://libav.org/documentation/doxygen/master/avio_8h.html#a853f5149136a27ffba3207d8520172a5
* https://lists.libav.org/pipermail/libav-api/2012-June/000547.html
* https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/avio_reading.c

## Using FFMpeg Binary

The way koel handles transcoding is by calling the ffmpeg binary telling it to convert to a format and output the result to STDOUT. This works, but this adds a runtime dependency on ffmpeg. It might be a worthy tradeoff considering how complicated using the ffmpeg library is. Using things like ffmpeg-static to include or download a version of ffmpeg or shipping a docker/appimage/flatpak could make this easy.

Upon further investigation, it seems that installing ffmpeg on fedora is non-trivial. It is available through RPM fusion.

Also, upon further investigation, it seems that transcoding to stdout and a file are two different things. Files have random access, [while pipes don't](https://stackoverflow.com/questions/25411836/ffmpeg-doesnt-work-with-mp4-and-stdout). Practically, this means that the duration doesn't show up in the audio bar at runtime and the file is played as an indefinite stream. This is a problem in koel (https://github.com/phanan/koel/issues/306#issue-149000104).

## Pre-Transcoding Files
For cases where the transcoded files are read very often, it makes sense to transcode the files as soon as they are uploaded. Here, we don't mind trading off space for CPU time. We can make this configurable later with some caching parameters.

## Formats
We want to transcode to formats which are one of two things.

1. Playable on many devices.
2. Low bandwidth.

We'd like to eventually support the following devices. Here are the formats they support.

* Google Assistant (https://developers.google.com/actions/assistant/responses#media_responses) 
  Says it will accept a properly formatted MP3. Deezer also says it has been able to somehow stream lossless flac to Google Assistant devices somehow.

  ![image](https://user-images.githubusercontent.com/3277097/44182765-47a15100-a0d6-11e8-9850-ffc420e1f9c5.png)

  https://support.deezer.com/hc/en-gb/articles/115003803629-Google-Home

* Amazon Alexa (https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html)

  Hmm, it says only up to 256kbps mp3 and AAC are supported. This is probably a constraint placed by low end alexa devices.

* Android (https://developer.android.com/guide/topics/media/media-formats#audio-codecs)

* iOS (https://stackoverflow.com/questions/1761460/supported-audio-file-formats-in-iphone) (https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/MultimediaPG/UsingAudio/UsingAudio.html)

  ![image](https://user-images.githubusercontent.com/3277097/44182978-2ab94d80-a0d7-11e8-9ad2-ca39a7fd04bf.png)

Based on these constraints, the following codecs should be supported:

* MP3 V0. Preferred for Google Assistant.
* AAC vbr quality 5 (2 channels). Preferred for iOS, Android, Alexa.

We will consider adding some lower bandwidth options when building the mobile applications.

## Needless Conversion
Conversion shouldn't be allowed in some cases like going between two lossless formats (AACv5 -> MP3v0), but there is no objective metric for whether a conversion should happen or not. For now, we'll let the user choose what format they want to stream their music at runtime and decide in constrained environments like the Google Assistant.

## TODO
* [x] #21
* [x] Respond to range requests from an io.Read + io.Seek (https://github.com/forte-music/core/commits/feature/streaming)
* [x] Given a file path, figure out how to transcode the file at that path to a format and bitrate.
* [x] Given a request for some set of bytes in a transcoded file, fulfill the request using a shared cached transcoder instance.
* [x] Make Transcoding Asynchronous
* [x] Handle Transcoding Errors
* [x] Use Actual Paths for Transcoded Files
* [x] Test TemporaryFiles
* [x] <strike>Test RangeStream</strike> (difficult to test, seems to work, low churn, should probably be moved to a library)
* [x] Test FileStream
* [x] <strike>Test TranscodingFileHandler</strike> (low risk, low reward)
* [x] <strike>Test Transcoder</strike> (can't really test the actual transcoding without a decoder, should probably test because of runtime borrow checking, can't easily replace the transcoding future)
* [x] Test TranscodeTarget (data container nothing to test)
* [x] Configurable FFMPEG Path (#51)

**Comment by 0xcaff** [comment]
It looks like transcoding is going to be a bit more difficult than I thought.

Here's the problem. Given an offset and a length, get `length` bytes at `offset` from the input stream decoded then encoded as the desired output stream type. It looks like there is no way for random access transcoding to mp3; all data up to `offset` needs to be transcoded. For transcoding to be efficient, the result needs to be cached. So that as the song is played on the client, the song isn't re-transcoded for every range request.

There are two parameters to a cache. Where to store the cached values and where how long to keep them in the cache for.

The cached values should be stored in memory. It is cheap to populate the cache (~1m to convert a 3m FLAC file to mp3 on an old machine) and storing the cache in memory, allows for handling evictions cheaply.

TODO: Think about how long items need to be kept in the cache.

**Comment by 0xcaff** [comment]
https://docs.rs/plru/0.1.1/plru/struct.Cache.html

**Comment by 0xcaff** [comment]
FFmpeg is the state of the art, but how to use their code isn't very discoverable due to lack of documentation or any sort of constraints in the type system. I've created a binary which can decode an audio and encode it into a CBR mp3.

Next up is designing the integration between this code and the endpoints.

**Comment by 0xcaff** [comment]
AWW YEAH! 2 is done!!! in process on the fly transcoding!

![image](https://user-images.githubusercontent.com/3277097/40823759-92663e44-653f-11e8-96a3-fb23357c65af.png)

**Comment by 0xcaff** [comment]
Unfortunately, the build is broken because of ffmpeg. https://github.com/0xcaff/docker-forte-core-build/issues/8

**Comment by 0xcaff** [comment]
Statically linking ffmpeg is kinda difficult. Using the automated configuration works in the docker image, but brings in tons of un-needed dependencies. https://circleci.com/gh/forte-music/core/376

It doesn't work on my local machine and fails silently because https://github.com/alexcrichton/pkg-config-rs/issues/68

The two options are:
* give it all the dependencies it needs bloating the binary and increasing complexity
* build a version of ffmpeg without un-needed features. some modification will need to be made to the rust wrapper because it tries to link every possibly needed extra library statically.

**Comment by 0xcaff** [comment]
The best bet is to probably compile our own version of ffmpeg. It looks like ffmpeg feature flags can be accessed through cargo and only needed dependencies are statically linked in. The other option doesn't give us enough control.

**Comment by 0xcaff** [comment]
ffmpeg is mostly statically linked at this point. A couple dependencies aren't linked though. The build should be updated to fail in this case. The debug binary is a 243mb file. This should probably be reduced.

**Comment by 0xcaff** [comment]
@Mcat12 What are your thoughts on making ffmpeg a runtime dependency? Instead of using the ffmpeg library, we could call the cli in a process to do transcoding and output the transcoded result to STDOUT.

## Pros
1. Builds would be faster and smaller.
2. Less code. There's about 150 lines of confusing ffmpeg code to do transcoding which transcode an entire file given a path. Making transcoding yield execution after some bytes requires using generators or a manually crafted state machine. The yielding transcoder will be more (complex) code.
3. It's easy to have a yielding transcoder with the CLI, just stop reading and backpressure will cause the process on the other end of the pipe to stop writing.

## Cons
1. Runtime dependency. It's not that hard of a runtime dependency to have though. It is in the package manager for many distros and could be easily bundled in a docker container.

**Comment by Mcat12** [comment]
If it's as simple as `apt install ffmpeg` or equivalent, then that's good. Just make sure we can handle all possible errors and that it's not fragile

**Comment by 0xcaff** [comment]
Just tested it playing a v0 mp3 transcoded from FLAC on the Google Home and it works!
